# Generated by Django 5.2.4 on 2025-08-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productsize_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='products/main/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sound_archive',
            field=models.FileField(blank=True, help_text='Загрузите .7z архив со звуками (media/products)', null=True, upload_to='products/'),
        ),
    ]
