# Generated by Django 5.2.4 on 2025-08-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesettings_product_sound_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sound_archive',
        ),
    ]
