# Generated by Django 5.2.4 on 2025-07-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_stripe_payment_intend_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
